name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Measure compilation time of Test with 0.8.17 --via-ir
        if: always()
        run: forge build

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: foundry-toolchain
        uses: foundry-rs/foundry-toolchain@v1.0.6
        with:
          version: nightly

      - name: Print forge version
        run: forge --version

      - name: Run tests
        run: forge test -vvv
